#### crowsnest.conf
#### This is the default config after installation.
#### It is also used as the default config in MainsailOS.
#### For details on how to configure this to your needs, see:
#### https://github.com/mainsail-crew/crowsnest/blob/v5/README.md


#####################################################################
####                                                            #####
####      Information about ports and according URL's           #####
####                                                            #####
#####################################################################
####                                                            #####
####    Port 8080 equals /webcam/?action=[stream/snapshot]      #####
####    Port 8081 equals /webcam2/?action=[stream/snapshot]     #####
####    Port 8082 equals /webcam3/?action=[stream/snapshot]     #####
####    Port 8083 equals /webcam4/?action=[stream/snapshot]     #####
####                                                            #####
####    Note: These ports are default for most Mainsail         #####
####    installations. Using any other port would involve       #####
####    changing the proxy configuration or using URLs          #####
####    with the specific port like                             #####
####    http://<ip>:<port>/?action=[stream/snapshot]            #####
####                                                            #####
#####################################################################


[crowsnest]
log_path: ~/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: true

[cam 1]
mode: ustreamer
port: 8080
# מצלמת המיקרוסופט
device: /dev/v4l/by-id/usb-Microsoft_Microsoft®_LifeCam_HD-3000-video-index0
resolution: 1900x1080
custom_flags: --host 0.0.0.0
max_fps: 15

[cam 2]
mode: ustreamer
port: 8081
# מצלמת ה-USB הכללית
device: /dev/v4l/by-id/usb-BC-231212-ZW_USB_Camera-video-index0
custom_flags: --host 0.0.0.0
resolution: 1900x1080
max_fps: 15
