Section "Device"
    Identifier "SPI Display"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier "Default Screen"
    Device "SPI Display"
    SubSection "Display"
        Modes "320x240"
    EndSubSection
EndSection
